### PR TITLE
Edition bump and dependency update

### PR DESCRIPTION
**Pull request by jonhoo**

### CODE REVIEW

**Comment by jonhoo** [comment]
This change is [Reviewable](https://reviewable.io/reviews/jonhoo/openssh-rs/31)

**Comment by NobodyXu** [comment]
Nice!

With edition 2021, we can use [field `rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) in `Cargo.toml`.

**Comment by jonhoo** [comment]
Good point! Want to send a quick PR?

**Comment by NobodyXu** [comment]
Sure!

**Pull request merged**
